#!/command/with-contenv bash

pid=$(pgrep -f 'run/s6/basedir/scripts/rc.init top (server)|(sensor).py')

if [[ ${pid} != "" ]]; then
    echo "s6-service [maltrail-server]: maltrail has been started by docker command, skipping starting service.."
    tail -f /dev/null
fi

cd ${VENV}

echo 'starting maltrail webserver..'
python -u server.py

